// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdluukzrwcvwtaclanla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbHV1a3pyd2N2d3RhY2xhbmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDc2NjksImV4cCI6MjA2OTg4MzY2OX0.3pzpeuxghtLNXp2_8CLMCIV2UidshnQ7lULMy6yFzWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});